name: Deploy Vite WatchTask App

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Create environment file
        working-directory: WatchTask
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_PEER_CONNECT_BACKOFF_MS: ${{ vars.VITE_PEER_CONNECT_BACKOFF_MS }}
          VITE_PEER_PING_INTERVAL_MS: ${{ vars.VITE_PEER_PING_INTERVAL_MS }}
          VITE_ADMIN_NAME: ${{ secrets.VITE_ADMIN_NAME }}
          VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}
          VITE_ADMIN_CODE: ${{ secrets.VITE_ADMIN_CODE }}
          VITE_CHUNK_SIZE: ${{ vars.VITE_CHUNK_SIZE }}
          VITE_CHUNK_DELAY_MS: ${{ vars.VITE_CHUNK_DELAY_MS }}
          VITE_DC_BUFFER_MAX: ${{ vars.VITE_DC_BUFFER_MAX }}
          VITE_DC_BUFFER_LOW: ${{ vars.VITE_DC_BUFFER_LOW }}
        run: |
          : "${VITE_PEER_CONNECT_BACKOFF_MS:=15000}"
          : "${VITE_PEER_PING_INTERVAL_MS:=5000}"
          : "${VITE_CHUNK_SIZE:=4}"
          : "${VITE_CHUNK_DELAY_MS:=50}"
          : "${VITE_DC_BUFFER_MAX:=262144}"
          : "${VITE_DC_BUFFER_LOW:=131072}"
          cat <<EOF > .env.production
          VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
          VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
          VITE_FIREBASE_DATABASE_URL=$VITE_FIREBASE_DATABASE_URL
          VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
          VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
          VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
          VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
          VITE_PEER_CONNECT_BACKOFF_MS=$VITE_PEER_CONNECT_BACKOFF_MS
          VITE_PEER_PING_INTERVAL_MS=$VITE_PEER_PING_INTERVAL_MS
          VITE_ADMIN_NAME=$VITE_ADMIN_NAME
          VITE_ADMIN_PASSWORD=$VITE_ADMIN_PASSWORD
          VITE_ADMIN_CODE=$VITE_ADMIN_CODE
          VITE_CHUNK_SIZE=$VITE_CHUNK_SIZE
          VITE_CHUNK_DELAY_MS=$VITE_CHUNK_DELAY_MS
          VITE_DC_BUFFER_MAX=$VITE_DC_BUFFER_MAX
          VITE_DC_BUFFER_LOW=$VITE_DC_BUFFER_LOW
          EOF

      - name: Install deps
        run: npm install --prefix WatchTask

      - name: Build
        run: npm run build --prefix WatchTask

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WatchTask/dist
